### ISSUE TITLE
Can't initialize properly - fopen (config/graph.xml, "wb") failed

### ISSUE THREAD

**Issue by pavitrakumar78** [ugo-nama-kun/gym_torcs#17]
Hi,

I am trying to get gym_torcs to work on my Ubuntu 14.04. When I execute the sample_experiement.py file, I get the following error:

```
gfParmSetStr: fopen (config/graph.xml, "wb") failed
```

Full log:
```
Fuel consumption disabled!
Car damages disabled!
Laptime limit disabled!
Image generation is ON!
Visual Properties Report
------------------------
Compatibility mode, properties unknown.
Waiting for request on port 3101
TORCS Experiment Start.
Episode : 0
Client connected on 3101..............
OpenAL backend info:
  Vendor: OpenAL Community
  Renderer: OpenAL Soft
  Version: 1.1 ALSOFT 1.14
  Available sources: 256
  Available buffers: 1024 or more
  Dynamic Sources: requested: 235, created: 235
  #static sources: 21
  #dyn sources   : 235
gfParmSetStr: fopen (config/graph.xml, "wb") failed
sw 64 - sh 64 - vw 64 - vh 64 - imgsize 12288
Traceback (most recent call last):
  File "example_experiment.py", line 26, in <module>
    ob = env.reset(relaunch=True)
  File "/home/pavitrakumar/Desktop/gym_torcs-master/gym_torcs.py", line 192, in reset
    self.observation = self.make_observaton(obs)
  File "/home/pavitrakumar/Desktop/gym_torcs-master/gym_torcs.py", line 272, in make_observaton
    image_rgb = self.obs_vision_to_image_rgb(raw_obs[names[8]])
  File "/home/pavitrakumar/Desktop/gym_torcs-master/gym_torcs.py", line 242, in obs_vision_to_image_rgb
    return np.array([r, g, b], dtype=np.uint8)
TypeError: long() argument must be a string or a number, not 'NoneType'
pavitrakumar@pavitrakumar-PC:~/Desktop/gym_torcs-master$ Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
Timeout for client answer
.
.
.
```

I am trying this on python 2.x with the necessary imports to make it work (print and division), but I am not sure where the requested file (graph.xml) is located.

**Comment by pavitrakumar78** [comment]
I was testing on py 2.x, so the destringify method converted everything into `None`. Removing all UTF-8 conversions made it work normally.

**Comment by xinleipan** [comment]
Hi @pavitrakumar78 , seems like you have solved this? How did you solve this?

**Comment by pavitrakumar78** [comment]
Hi @xinleipan,

As I have mentioned in my previous comment, I was testing this code on python 2.7 (required is python 3.x) . So, there seemed to be some problem in the functions that were returning output after decoding them as utf-8. I remove all such statements and it worked properly. 
The file I am using for python 2.7 is:

[snakeoil3_gym.py.zip](https://github.com/ugo-nama-kun/gym_torcs/files/786562/snakeoil3_gym.py.zip)

**Comment by s7ev3n** [comment]
@pavitrakumar78 Thx for you file!

**Comment by bjane123** [comment]
I am testing this code on python3.5. And based on python 3.5 the utf-8 is not the problem. But This question never be solved. 
If anyone has some advise for me? Thanks.

**Comment by pavitrakumar78** [comment]
@bjane123 Not sure I understand you. The problem I had in py27was due to UTF conversion. Once I fixed it, there were no more problems.

**Comment by BCWang93** [comment]
@bjane123  Hi.Did you solved this probelm?I am also this problem recently.Can you help me?Thanks!

**Comment by sjtusmartboy** [comment]
@bjane123 I have the same problem with you. Did you solve it?

**Comment by bartoszptak** [comment]
> @bjane123 I have the same problem with you. Did you solve it?

Hi guys, here Ubuntu 18.04 and Python 3.6. 
For me, the solution to the problem was to use `sudo` with each call to `torcs`.

**Comment by James-Zhang-23** [comment]
How do you make sudo to all call to torcs?

**Comment by James-Zhang-23** [comment]
@bartoszptak How do you use sudo with each call to torcs?

**Comment by YFrisch** [comment]
> @bartoszptak How do you use sudo with each call to torcs?

In snakeoil3_gym.py change the `os.system(...)` commands such that they run with sudo rights.

E.g. change `os.system(pkill torcs)` to `os.system(f'echo {sudo_pw}|sudo -S pkill torcs')` where `sudo_pw` is your password saved as a variable.

I think they are all inside the `setup_connection(self)` method of `class Client()` from snakeoil3_gym.py.
Starting from line 167 I edited every system command:

```
            try:
                sockdata,addr= self.so.recvfrom(data_size)
                sockdata = sockdata.decode('utf-8')
            except socket.error as emsg:
                print("Waiting for server on %d............" % self.port)
                print("Count Down : " + str(n_fail))
                if n_fail < 0:
                    print("relaunch torcs")
                    os.system(f'echo {sudo_pw}|sudo -S pkill torcs')
                    time.sleep(1.0)
                    if self.vision is False:
                        os.system(f'echo {sudo_pw}|sudo -S torcs -nofuel -nodamage -nolaptime &')
                    else:
                        os.system(f'echo {sudo_pw}|sudo -S torcs -nofuel -nodamage -nolaptime -vision &')

                    time.sleep(1.0)
                    os.system(f' echo {sudo_pw}| sudo -S sh autostart.sh')
                    n_fail = 5
                n_fail -= 1
```
