### ISSUE TITLE
Running multiple gym_torcs experiments in parallel on the same machine

### ISSUE THREAD

**Issue by Santara** [ugo-nama-kun/gym_torcs#27]
Hi,
I want to launch multiple ```gym_torcs``` environments on my machine so that I can run multiple simulations in parallel. Currently when I try to launch an extra simulation, the previous one crashes. The problem is likely the fact that the client and server always talk through the ```3001``` port. Is there a way to assign different ports to different instances of ```gym_torcs```?
Thank you,
Anirban

**Comment by muupan** [comment]
Hi,

You can use https://github.com/ugo-nama-kun/gym_torcs/pull/3, though it is not merged yet.

**Comment by Santara** [comment]
@muupan I did and it worked! I appreciate your job! Hope your PR gets merged soon :)
