### ISSUE TITLE
More data from Server ?

### ISSUE THREAD

**Issue by s7ev3n** [ugo-nama-kun/gym_torcs#35]
I looked into the TORCS manual, and get to know that you can export more sensor data through tCarElt, any idea how to achieve that? Many thanks!

**Comment by lyokka** [comment]
Hello s7ev3n

May I ask how did you achieve this? I would like to get some information like current road curvatures

**Comment by s7ev3n** [comment]
I did get current road curvature info by adding some lines(407-420) of code which in the attachment. Also, you should accordingly make snakeoil3_gym.py to accept the new sensor data from server. Hope this helps you.
[scr_server.zip](https://github.com/ugo-nama-kun/gym_torcs/files/1425843/scr_server.zip)
