### ISSUE TITLE
Error while 'making' Vtorcs

### ISSUE THREAD

**Issue by sahiliitm** [ugo-nama-kun/gym_torcs#8]
Hi,

When I execute .`/configure` in vtorcs folder, the command runs smoothly. However when i execute the next command which is `make` I get the error as documented in this [pastebin link](http://pastebin.com/RbL0SvA1). 
Any idea why I get so many errors? I suspect that the makefile is not well formatted.

Thanks

**Comment by AliBaheri** [comment]
Hi @sahiliitm 

I do have the issue. Would you plz give some info how did you resolve this?
